In [1]:
import numpy as np

In [2]:
x = np.arange(9).reshape(3, 3)
y = np.full((3, 3), 2)
print(x)
print()
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [3]:
print(np.sum(x))
print()
print(np.sum(x, axis = 0))
print()
print(np.sum(x, axis = 1))

36

[ 9 12 15]

[ 3 12 21]


##### Arithmetic operations

In [4]:
print(np.add(x, y))
print()
print(np.subtract(x, y))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [5]:
print(np.multiply(x, y))
print()
print(np.divide(x, y))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [6]:
x1 = np.arange(6)
print(np.power(x1, 2))

[ 0  1  4  9 16 25]


##### Trigonometic functions

In [7]:
x2 = np.arange(0, 370, 30)
x2

array([  0,  30,  60,  90, 120, 150, 180, 210, 240, 270, 300, 330, 360])

In [8]:
x2 = x2*np.pi / 180
x3 = np.sin(x2)
x3.astype(np.float16)

array([ 0.   ,  0.5  ,  0.866,  1.   ,  0.866,  0.5  ,  0.   , -0.5  ,
       -0.866, -1.   , -0.866, -0.5  , -0.   ], dtype=float16)

In [9]:
np.cos(x2)

array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00, -8.66025404e-01,
       -5.00000000e-01, -1.83697020e-16,  5.00000000e-01,  8.66025404e-01,
        1.00000000e+00])

In [10]:
np.tan(x2)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16,  5.77350269e-01,
        1.73205081e+00,  5.44374645e+15, -1.73205081e+00, -5.77350269e-01,
       -2.44929360e-16])