In [1]:
import numpy as np

##### np array of zeros

In [2]:
num0 = np.zeros((4, 4), dtype = int)
print(num0)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##### np array of ones

In [3]:
num1 = np.ones((5, 7), dtype = int)
print(num1)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


##### np array with ones on the diagonal and zeros elsewhere

In [4]:
num3 = np.eye(10, dtype = int)
print(num3)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


##### np array filled with a specified number.

In [5]:
num4 = np.full((6,8), 10)
num41 = np.full((5, 5), np.inf)
print("num4 is:\n",num4)
print("num41 is:\n", num41)

num4 is:
 [[10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]]
num41 is:
 [[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


##### np array range

In [6]:
num5 = np.arange(10)
num52 = np.arange(10.0)
num53 = np.arange(0, 20, 2)
print(num5)
print(num52)
print(num53)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0  2  4  6  8 10 12 14 16 18]


##### np linspace
Return evenly spaced numbers over a specified interval.

In [7]:
num6 = np.linspace(0, 20, num=5)
print("num6 is:\n",num6)

num6 is:
 [ 0.  5. 10. 15. 20.]


##### np random numbers

In [8]:
num7 = np.random.random(3) # Return random floats in a half-open interval
num71 = np.random.rand(3, 2) # Create an array of random samples from a uniform distribution
num72 = np.random.randn(3, 2) # normal (Gaussian) distribution of mean 0 and variance 1
print("num7 is:\n",num7)
print("num71 is:\n", num71)
print("num72 is:\n",num72)

num7 is:
 [0.04373792 0.83527122 0.39929366]
num71 is:
 [[0.09645151 0.00975146]
 [0.5742154  0.09902062]
 [0.89251356 0.92215085]]
num72 is:
 [[-0.47929205 -1.21775277]
 [-0.41510596  0.28878384]
 [ 1.43538408 -0.21651555]]


##### NumPy indexing

In [9]:
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a[1]

2

In [11]:
print(a[-1])
print(a[:])
print(a[:-1])

18
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16]


In [12]:
a.dtype

dtype('int32')

In [13]:
a.size

10

In [14]:
a.shape

(10,)

In [15]:
b = a.reshape((5, 2))
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [16]:
b.dtype

dtype('int32')

In [17]:
b.size

10

In [18]:
b.shape

(5, 2)

In [19]:
b[3, 1]

14