In [1]:
import numpy as np

In [2]:
x = np.arange(16).reshape(4, 4)
y = np.eye(4, dtype="int")
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
print(y)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
x.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [5]:
x.trace()

30

In [6]:
y.trace()

4

In [7]:
np.linalg.inv(x)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [8]:
np.matmul(x, y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.inner(x, y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.outer(x, y)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1],
       [ 2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2],
       [ 3,  0,  0,  0,  0,  3,  0,  0,  0,  0,  3,  0,  0,  0,  0,  3],
       [ 4,  0,  0,  0,  0,  4,  0,  0,  0,  0,  4,  0,  0,  0,  0,  4],
       [ 5,  0,  0,  0,  0,  5,  0,  0,  0,  0,  5,  0,  0,  0,  0,  5],
       [ 6,  0,  0,  0,  0,  6,  0,  0,  0,  0,  6,  0,  0,  0,  0,  6],
       [ 7,  0,  0,  0,  0,  7,  0,  0,  0,  0,  7,  0,  0,  0,  0,  7],
       [ 8,  0,  0,  0,  0,  8,  0,  0,  0,  0,  8,  0,  0,  0,  0,  8],
       [ 9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  9],
       [10,  0,  0,  0,  0, 10,  0,  0,  0,  0, 10,  0,  0,  0,  0, 10],
       [11,  0,  0,  0,  0, 11,  0,  0,  0,  0, 11,  0,  0,  0,  0, 11],
       [12,  0,  0,  0,  0, 12,  0,  0,  0,  0, 12,  0,  0,  0,  0, 12],
       [13,  0,  0,  0,  0, 13,  0,  0,  0,  0, 13,

In [11]:
np.linalg.det(x)

-2.9582283945787796e-30

In [12]:
np.linalg.eig(x)

(array([ 3.24642492e+01, -2.46424920e+00,  1.92979794e-15, -4.09576009e-16]),
 array([[-0.11417645, -0.7327781 ,  0.54500164,  0.00135151],
        [-0.3300046 , -0.28974835, -0.68602671,  0.40644504],
        [-0.54583275,  0.15328139, -0.2629515 , -0.8169446 ],
        [-0.76166089,  0.59631113,  0.40397657,  0.40914805]]))

In [13]:
np.linalg.solve(x, y)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [14]:
z = x + y
z

array([[ 1,  1,  2,  3],
       [ 4,  6,  6,  7],
       [ 8,  9, 11, 11],
       [12, 13, 14, 16]])

In [15]:
z = x - y
z

array([[-1,  1,  2,  3],
       [ 4,  4,  6,  7],
       [ 8,  9,  9, 11],
       [12, 13, 14, 14]])